#!/usr/bin/env python3

"""
Day 22 - Graph 1
FIFO Functional Coverage by Verification Strategy

Project:
AI-Driven RTL Test Generation,
Coverage Analysis and Verification

Input:
    results/fifo/day22/day22_graph_data.json

Output:
    graphs/day22_graph1_strategy_coverage.png

Also creates:
    results/fifo/day22/graph1_strategy_coverage.png

Purpose:
Compare the measured FIFO functional coverage of:
    1. Manual-directed verification
    2. Random verification
    3. Feedback-driven verification

The graph uses the actual measured Day-20 strategy results.
"""

import json
import shutil
import sys
from pathlib import Path

import matplotlib.pyplot as plt


# ============================================================
# PATHS
# ============================================================

ROOT = Path(__file__).resolve().parents[1]

DAY22_DIR = (
    ROOT
    / "results"
    / "fifo"
    / "day22"
)

PRIMARY_INPUT = (
    DAY22_DIR
    / "day22_graph_data.json"
)

FALLBACK_INPUT = (
    DAY22_DIR
    / "graph_data.json"
)

GRAPH_OUTPUT = (
    ROOT
    / "graphs"
    / "day22_graph1_strategy_coverage.png"
)

RESULT_OUTPUT = (
    DAY22_DIR
    / "graph1_strategy_coverage.png"
)


# ============================================================
# LOAD JSON
# ============================================================

def load_json(path):

    if not path.exists():

        raise FileNotFoundError(
            f"Required graph-data file not found: {path}"
        )

    try:

        with path.open(
            "r",
            encoding="utf-8"
        ) as file:

            data = json.load(file)

    except json.JSONDecodeError as exc:

        raise ValueError(
            f"Invalid JSON in {path}: "
            f"line {exc.lineno}, "
            f"column {exc.colno}: "
            f"{exc.msg}"
        ) from exc

    if not isinstance(
        data,
        dict
    ):

        raise ValueError(
            "Day 22 graph data must be a JSON object."
        )

    return data


# ============================================================
# SELECT INPUT
# ============================================================

def select_input():

    if PRIMARY_INPUT.exists():

        return PRIMARY_INPUT

    if FALLBACK_INPUT.exists():

        return FALLBACK_INPUT

    raise FileNotFoundError(
        "Neither day22_graph_data.json "
        "nor graph_data.json exists."
    )


# ============================================================
# SAFE FLOAT
# ============================================================

def safe_float(
    value,
    default=0.0
):

    try:

        return float(value)

    except (
        TypeError,
        ValueError
    ):

        return default


# ============================================================
# FRIENDLY STRATEGY NAME
# ============================================================

def friendly_name(name):

    normalized = str(
        name
    ).strip().lower()


    mapping = {

        "manual_directed":
            "Manual Directed",

        "manual":
            "Manual Directed",

        "random":
            "Random",

        "feedback_driven":
            "Feedback Driven",

        "ai":
            "Feedback Driven",

        "ai_feedback":
            "Feedback Driven",

        "proposed":
            "Feedback Driven",
    }


    return mapping.get(
        normalized,
        str(name).replace(
            "_",
            " "
        ).title()
    )


# ============================================================
# GET STRATEGY DATA
# ============================================================

def extract_strategy_data(data):

    # --------------------------------------------------------
    # CURRENT DAY-22 SCHEMA
    # --------------------------------------------------------

    strategies = data.get(
        "day20_strategy_comparison"
    )


    # --------------------------------------------------------
    # OLD-SCHEMA FALLBACK
    # --------------------------------------------------------

    if strategies is None:

        strategies = data.get(
            "strategy_comparison"
        )


    # --------------------------------------------------------
    # SECOND FALLBACK:
    # use graph_specs generated by day22_data_builder.py
    # --------------------------------------------------------

    if strategies is None:

        graph_specs = data.get(
            "graph_specs",
            {}
        )

        graph1 = graph_specs.get(
            "graph_01_strategy_coverage",
            {}
        )

        x_values = graph1.get(
            "x",
            []
        )

        y_values = graph1.get(
            "y",
            []
        )


        if (
            isinstance(
                x_values,
                list
            )
            and isinstance(
                y_values,
                list
            )
            and len(
                x_values
            )
            == len(
                y_values
            )
            and len(
                x_values
            )
            > 0
        ):

            return [
                {
                    "strategy":
                        x,

                    "coverage_percent":
                        safe_float(
                            y
                        ),
                }

                for x, y
                in zip(
                    x_values,
                    y_values
                )
            ]


    if not isinstance(
        strategies,
        list
    ):

        raise ValueError(
            "Strategy data not found. Expected "
            "'day20_strategy_comparison'."
        )


    if not strategies:

        raise ValueError(
            "Strategy comparison list is empty."
        )


    normalized = []


    for row in strategies:

        if not isinstance(
            row,
            dict
        ):

            continue


        strategy = row.get(
            "strategy"
        )

        coverage = row.get(
            "coverage_percent"
        )


        if strategy is None:

            continue


        if coverage is None:

            continue


        normalized.append(
            {
                "strategy":
                    strategy,

                "coverage_percent":
                    safe_float(
                        coverage
                    ),
            }
        )


    if not normalized:

        raise ValueError(
            "No usable strategy coverage records were found."
        )


    return normalized


# ============================================================
# GENERATE GRAPH
# ============================================================

def generate_graph(
    strategies
):

    labels = [
        friendly_name(
            row[
                "strategy"
            ]
        )

        for row
        in strategies
    ]


    coverage = [
        row[
            "coverage_percent"
        ]

        for row
        in strategies
    ]


    # --------------------------------------------------------
    # Create figure
    # --------------------------------------------------------

    fig, ax = plt.subplots(
        figsize=(
            10,
            6
        )
    )


    bars = ax.bar(
        labels,
        coverage,
        width=0.62
    )


    # --------------------------------------------------------
    # Titles and labels
    # --------------------------------------------------------

    ax.set_title(
        "FIFO Functional Coverage by Verification Strategy",
        fontsize=15,
        pad=15
    )

    ax.set_xlabel(
        "Verification Strategy",
        fontsize=12
    )

    ax.set_ylabel(
        "Functional Coverage (%)",
        fontsize=12
    )


    # --------------------------------------------------------
    # Coverage scale
    # --------------------------------------------------------

    max_value = max(
        coverage
    )


    upper_limit = max(
        105.0,
        max_value
        + 10.0
    )


    ax.set_ylim(
        0,
        upper_limit
    )


    # --------------------------------------------------------
    # Grid
    # --------------------------------------------------------

    ax.grid(
        axis="y",
        linestyle="--",
        alpha=0.35
    )


    # --------------------------------------------------------
    # Value labels
    # --------------------------------------------------------

    for bar, value in zip(
        bars,
        coverage
    ):

        ax.text(
            bar.get_x()
            + bar.get_width()
            / 2.0,

            bar.get_height()
            + 1.5,

            f"{value:.1f}%",

            ha="center",
            va="bottom",
            fontsize=11
        )


    # --------------------------------------------------------
    # Explanatory footer
    # --------------------------------------------------------

    fig.text(
        0.5,
        0.01,
        "Measured FIFO functional coverage using the common 10-point coverage model.",
        ha="center",
        fontsize=9
    )


    fig.tight_layout(
        rect=(
            0,
            0.04,
            1,
            1
        )
    )


    # --------------------------------------------------------
    # Save report-quality PNG
    # --------------------------------------------------------

    GRAPH_OUTPUT.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    RESULT_OUTPUT.parent.mkdir(
        parents=True,
        exist_ok=True
    )


    fig.savefig(
        GRAPH_OUTPUT,
        dpi=300,
        bbox_inches="tight"
    )


    plt.close(
        fig
    )


    # --------------------------------------------------------
    # Compatibility/result copy
    # --------------------------------------------------------

    shutil.copy2(
        GRAPH_OUTPUT,
        RESULT_OUTPUT
    )


# ============================================================
# MAIN
# ============================================================

def main():

    try:

        input_file = (
            select_input()
        )


        data = load_json(
            input_file
        )


        strategies = (
            extract_strategy_data(
                data
            )
        )


        generate_graph(
            strategies
        )


        print(
            "=" * 72
        )

        print(
            "DAY 22 - GRAPH 1"
        )

        print(
            "=" * 72
        )

        print(
            "Graph                       : Strategy Coverage Comparison"
        )

        print(
            "Source                      :",
            input_file.relative_to(
                ROOT
            )
        )

        print(
            "Strategies                  :",
            len(
                strategies
            )
        )

        print(
            "-" * 72
        )


        for row in strategies:

            print(
                f"{friendly_name(row['strategy']):28s}: "
                f"{row['coverage_percent']:.2f}%"
            )


        print(
            "-" * 72
        )

        print(
            "Graph output                :",
            GRAPH_OUTPUT.relative_to(
                ROOT
            )
        )

        print(
            "Result copy                 :",
            RESULT_OUTPUT.relative_to(
                ROOT
            )
        )

        print(
            "GRAPH 1 STATUS              : PASS"
        )

        print(
            "=" * 72
        )

        print(
            "GRAPH 1 GENERATION: PASS"
        )


        return 0


    except (
        FileNotFoundError,
        ValueError,
        KeyError,
        TypeError,
        OSError
    ) as exc:

        print(
            "GRAPH 1 GENERATION: FAIL"
        )

        print(
            f"ERROR: {exc}"
        )

        return 1


if __name__ == "__main__":

    sys.exit(
        main()
    )
